<div style='width: 100%; text-align: center;'> <h1> Numpy Beginner Tutorial 1. </h1> </div>
<img alt="NumPy" src="https://camo.githubusercontent.com/37d9964b95f38c96ed2cce75182f7ebda4b90f64/68747470733a2f2f676863646e2e7261776769742e6f72672f6e756d70792f6e756d70792f6d61737465722f6272616e64696e672f69636f6e732f7072696d6172792f6e756d70796c6f676f2e737667" height="60" data-canonical-src="https://ghcdn.rawgit.org/numpy/numpy/master/branding/icons/primary/numpylogo.svg" style="max-width:100%;">

<p>NumPy is the fundamental package needed for scientific computing with Python.</p>
<ul>
    <li><strong>Website:</strong> <a href="https://www.numpy.org" rel="nofollow">https://www.numpy.org</a></li>
    <li><strong>Documentation:</strong> <a href="https://numpy.org/doc" rel="nofollow">https://numpy.org/doc</a></li>
</ul>
<p>Benefits of Numpy:</p>
<ul>
    <li>a powerful N-dimensional array object</li>
    <li>sophisticated (broadcasting) functions</li>
    <li>tools for integrating C/C++ and Fortran code</li>
    <li>useful linear algebra, Fourier transform, and random number capabilities</li>
</ul>

In [18]:
import numpy as np

In [7]:
# passing list to numpy array.
num_list = [1,2,3,4,5]
np.array(num_list)

array([1, 2, 3, 4, 5])

In [10]:
# ndarray, Matrix
matrix = np.array([[1,2,3,4,5], [6,7,8,9,10]])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
# Show size and Dimension of array
# 2 rows, 5 columns. (2 x 3)
# add image here to show rows and column here.
matrix.shape

(2, 5)

In [14]:
# Check Type of elements in array
matrix.dtype

dtype('int64')

In [16]:
# check rows count
matrix.ndim

2

In [19]:
# check type of whole matrix
print(type(matrix))

<class 'numpy.ndarray'>


In [28]:
# Generate number range.
gen_list = np.arange(10)
gen_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
gen_num = np.arange(10000)

Execution Time Test

In [36]:
# Execution time to loop over list.
# Take cube of the list without numpy.
# Output: It takes 3.54 milliseconds to loop over list.

%timeit [i**3 for i in gen_num]

3.54 ms ± 13.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
gen_num_numpy = np.arange(10000)

In [41]:
# Execution time to cube over numpy array list
# Output: It takes 39.8 micro-seconds to loop over list.

%timeit gen_num_numpy**3

38.5 µs ± 665 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [43]:
# Generate two lists.

l_1 = range(10000)
l_2 = [i**2 for i in range(10000)]

In [46]:
# Multiply two list.

%timeit list(map(lambda x,y: x*y, l_1, l_2))

2.28 ms ± 57.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [48]:
array_1 = np.array(l_1)
array_2 = np.array(l_2)

In [50]:
# Multiply using Numpy array.

%timeit array_1 * array_2

14 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [53]:
# Generate customize array using starting, endpoint and skip strategy.

# Syntax:
# np.arange(start_number, end_number, skip)

np.arange(2,10,2)

array([2, 4, 6, 8])

In [55]:
# generate array with 2 rows and 3 columns.
# Initialized with zeros

np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [58]:
# Generate ones
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [60]:
# Identity Matrix. (All diagonal values are 1 and remaning are 0)
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [70]:
# 3 x 3 matrix with specific value 

# Syntax
# np.full(matrix_size, value_to_fill, type_of_value)

without_type_matrix = np.full((3,3), 2.2)

with_type_matrix = np.full((3,3), 2.2, dtype=np.int)

print('Without Type Matrix: \n\n', without_type_matrix, '\n\n', 
      'With Type: \n\n', with_type_matrix)


Without Type Matrix: 

 [[ 2.2  2.2  2.2]
 [ 2.2  2.2  2.2]
 [ 2.2  2.2  2.2]] 

 With Type: 

 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [73]:
# Square Matrix with provided diagonal values.

np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [75]:
# stack array horizontally

vector_array = np.array([1,2,3])

In [78]:
np.tile(vector_array,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [80]:
# get random number using numpy

np.random.random()

0.5326808666392107

In [84]:
# random value between range.(2 and 50)

50 * np.random.random() + 2

32.39844708253006

In [85]:
# Matrix of random values

np.random.random([3,3])

array([[ 0.22483074,  0.12050452,  0.35029188],
       [ 0.38631721,  0.98479081,  0.53895867],
       [ 0.36604278,  0.82122434,  0.45071215]])