<div style='width: 100%; text-align: center;'> <h1> Numpy Tutorial 2 </h1> </div>
<img alt="NumPy" src="https://camo.githubusercontent.com/37d9964b95f38c96ed2cce75182f7ebda4b90f64/68747470733a2f2f676863646e2e7261776769742e6f72672f6e756d70792f6e756d70792f6d61737465722f6272616e64696e672f69636f6e732f7072696d6172792f6e756d70796c6f676f2e737667" height="60" data-canonical-src="https://ghcdn.rawgit.org/numpy/numpy/master/branding/icons/primary/numpylogo.svg" style="max-width:100%;">

<p>NumPy is the fundamental package needed for scientific computing with Python.</p>
<ul>
    <li><strong>Website:</strong> <a href="https://www.numpy.org" rel="nofollow">https://www.numpy.org</a></li>
    <li><strong>Documentation:</strong> <a href="https://numpy.org/doc" rel="nofollow">https://numpy.org/doc</a></li>
</ul>
<p>Benefits of Numpy:</p>
<ul>
    <li>a powerful N-dimensional array object</li>
    <li>sophisticated (broadcasting) functions</li>
    <li>tools for integrating C/C++ and Fortran code</li>
    <li>useful linear algebra, Fourier transform, and random number capabilities</li>
</ul>

In [2]:
import numpy as np

In [9]:
# Split data equally into 100 parts and range is 1,50.
# 100 values equally spaced between 1-50.

arr_1 = np.linspace(1,50,100)
arr_1

array([  1.        ,   1.49494949,   1.98989899,   2.48484848,
         2.97979798,   3.47474747,   3.96969697,   4.46464646,
         4.95959596,   5.45454545,   5.94949495,   6.44444444,
         6.93939394,   7.43434343,   7.92929293,   8.42424242,
         8.91919192,   9.41414141,   9.90909091,  10.4040404 ,
        10.8989899 ,  11.39393939,  11.88888889,  12.38383838,
        12.87878788,  13.37373737,  13.86868687,  14.36363636,
        14.85858586,  15.35353535,  15.84848485,  16.34343434,
        16.83838384,  17.33333333,  17.82828283,  18.32323232,
        18.81818182,  19.31313131,  19.80808081,  20.3030303 ,
        20.7979798 ,  21.29292929,  21.78787879,  22.28282828,
        22.77777778,  23.27272727,  23.76767677,  24.26262626,
        24.75757576,  25.25252525,  25.74747475,  26.24242424,
        26.73737374,  27.23232323,  27.72727273,  28.22222222,
        28.71717172,  29.21212121,  29.70707071,  30.2020202 ,
        30.6969697 ,  31.19191919,  31.68686869,  32.18

In [10]:
# Check how much memory used by arr_1 in term of bytes. 
arr_1.itemsize

8

In [12]:
np.arange(18).shape

(18,)

In [15]:
# Change shape. 2 matrix of 3 x 3
reshape_arr = np.arange(18).reshape(2,3,3)

In [17]:
reshape_arr.shape

(2, 3, 3)

In [19]:
temp_arr = np.array([2,4,5,8,10,12,14,16,18])

In [25]:
# print different index elements in array at once.
temp_arr[[2,4,6]]

array([ 5, 10, 14])

In [29]:
arr_2 = np.array([[1,2,3,4], [6,7,8,9], [3,6,0,3]])
arr_2

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [3, 6, 0, 3]])

In [36]:
# 2d array values retrieve
arr_2[0,3]

4

In [38]:
# Check values using operators.
arr_2 > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]], dtype=bool)

In [43]:
arr_2[(arr_2 > 2 & (arr_2 < 5))]

array([1, 2, 3, 4, 6, 7, 8, 9, 3, 6, 3])

In [44]:
# It is just referencing not make copy.
arr_reference = arr_2

In [45]:
# separate object by using copy.
arr_copy = arr_2.copy()

In [48]:
# Check array sharing memory or not
np.shares_memory(arr_2, arr_copy)

False

In [52]:
# take transpose of arr_2
arr_2.T

array([[1, 6, 3],
       [2, 7, 6],
       [3, 8, 0],
       [4, 9, 3]])

In [55]:
#Compare matrix element by element
arr_2 == arr_copy

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [62]:
np.hstack((arr_2, arr_copy))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [6, 7, 8, 9, 6, 7, 8, 9],
       [3, 6, 0, 3, 3, 6, 0, 3]])

In [64]:
np.sin(arr_2)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [ 0.14112001, -0.2794155 ,  0.        ,  0.14112001]])

In [66]:
np.cos(arr_2)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.9899925 ,  0.96017029,  1.        , -0.9899925 ]])

In [68]:
np.sum(arr_1)

2550.0

In [70]:
np.median(arr_2)

3.5

In [72]:
arr_1.std()

14.287246791296807

In [76]:
# Determinant of matrix and inverse

det_arr = np.arange(1,10).reshape(3,3)
np.linalg.det(det_arr)

-9.5161973539299405e-16

In [78]:
# Inverse of matrix
np.linalg.inv(det_arr)

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [81]:
matrix_transpose = det_arr.T
matrix_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
# Dot product
np.dot(det_arr, matrix_transpose)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])